os:
  - linux

language: php

php:
  - '5.6.30'
  
before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  
before_install:
  - mysql -e 'CREATE DATABASE homestead_test;'
  #- if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" || ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then echo "include_path='.:/home/travis/.phpenv/versions/$(phpenv version-name)/lib/php/pear'" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  
script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php --standard=phpcs.xml app/Http/Controllers
  #- npm run production
  #- jshint resources/assets/js/modules/*

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor
